on:
  - push

jobs:
  build_and_deploy_jupyter_book:
    environment:
      name: github-pages

    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@main

    - name: Build Jupyter Book
      run: |
        pip install -U "jupyter-book<2.0.0" "pydata-sphinx-theme==0.15.3" "sphinx-book-theme<1.1.0" "sphinx<7"

        jupyter-book clean .
        jupyter-book build .

    - name: Upload artifact
      uses: actions/upload-pages-artifact@main
      with:
        path: "_build/html"

    - name: Deploy Jupyter Book to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@main
